import { z } from 'zod';
const num = z.number().finite();
const id = z.string().min(1).max(128);
const color = z.string().regex(/^#[\da-f]{6}$/i);
const pose = z.object({
  x: num.min(-2).max(2),
  y: num.min(-2).max(2),
  z: num.min(-3).max(3),
  rx: num,
  ry: num,
  rz: num,
  zoom: num.min(0.25).max(4),
  fov: num.min(20).max(80),
  focusX: num.min(0).max(1),
  focusY: num.min(0).max(1),
  autoFocus: z.boolean(),
});
const text = z.object({
  id,
  kind: z.literal('text'),
  text: z.string().max(50000),
  x: num,
  y: num,
  width: num.min(0.01).max(2),
  size: num.min(0.005).max(1),
  font: z.enum(['Inter', 'Arial', 'Georgia', 'monospace']),
  weight: num.min(100).max(900),
  color,
  align: z.enum(['left', 'center', 'right']),
  animation: z.enum(['none', 'simple', 'typewriter', 'letters', 'words', 'blur']),
  animationOffset: num.min(0).optional(),
  start: num.min(0),
  duration: num.min(0.01),
  end: num.min(0),
  opacity: num.min(0).max(1),
});
const logo = z.object({
  id,
  kind: z.literal('logo'),
  assetId: id,
  x: num,
  y: num,
  width: num.min(0.001).max(2),
  opacity: num.min(0).max(1),
  start: num.min(0),
  end: num.min(0),
});
const watermark = z.object({
  enabled: z.boolean(),
  kind: z.enum(['image', 'text']),
  assetId: id.optional(),
  text: z.string().max(500),
  font: z.enum(['Inter', 'Arial', 'Georgia', 'monospace']),
  weight: num.min(100).max(900),
  color,
  position: z.enum([
    'top-left',
    'top',
    'top-right',
    'left',
    'center',
    'right',
    'bottom-left',
    'bottom',
    'bottom-right',
  ]),
  size: num.min(0.005).max(1),
  opacity: num.min(0).max(1),
  margin: num.min(0).max(0.5),
});
const scene = z.object({
  id,
  name: z.string().max(500),
  kind: z.enum(['media', 'text']),
  assetId: id.optional(),
  duration: num.min(0.05).max(86400),
  trimIn: num.min(0),
  trimOut: num.min(0),
  loop: z.boolean(),
  sourceOffset: num.min(0).optional(),
  pose,
  frame: z.object({
    kind: z.enum(['plain', 'laptop', 'phone', 'monitor']),
    radius: num.min(0).max(0.2),
    border: num.min(0).max(0.1),
    padding: num.min(0).max(0.2),
    color,
    header: z.boolean(),
    fit: z.enum(['fit', 'fill']),
    cropX: num.min(0).max(1),
    cropY: num.min(0).max(1),
    cropZoom: num.min(1).max(4),
  }),
  background: z.object({
    kind: z.enum(['color', 'gradient', 'image', 'transparent']),
    color,
    color2: color.optional(),
    angle: num.min(-360).max(360).optional(),
    assetId: id.optional(),
    fit: z.enum(['fit', 'fill']),
    x: num.min(0).max(1),
    y: num.min(0).max(1),
  }),
  blur: num.min(0).max(1),
  focusWidth: num.min(0).max(1).default(0.12),
  dofEnabled: z.boolean().default(true),
  maxBlur: num.min(0).max(1).default(0.7),
  shadow: z.enum(['off', 'small', 'medium', 'large']),
  shadowIntensity: num.min(0).max(1),
  layers: z.array(z.discriminatedUnion('kind', [text, logo])),
  logo: watermark.optional(),
  keyframes: z.array(
    z.object({
      id,
      time: num.min(0),
      pose,
      easing: z.enum(['linear', 'ease', 'in', 'out', 'inOut', 'smooth', 'custom']),
      easingWindow: z.tuple([num.min(0).max(1), num.min(0).max(1)]).optional(),
      bezier: z.tuple([
        num.min(0).max(1),
        num.min(-2).max(3),
        num.min(0).max(1),
        num.min(-2).max(3),
      ]),
    }),
  ),
  transition: z.object({
    kind: z.enum(['cut', 'fade', 'push', 'zoom', 'wipe', 'blur']),
    duration: num.min(0).max(30),
  }),
  points: z.array(
    z.object({
      x: num.min(0).max(1),
      y: num.min(0).max(1),
      w: num.min(0).max(1),
      h: num.min(0).max(1),
    }),
  ),
  seed: num,
});
export const projectSchema = z.object({
  version: z.literal(1),
  id,
  name: z.string().max(500),
  createdAt: num,
  updatedAt: num,
  output: z.object({ width: num.min(1).max(16384), height: num.min(1).max(16384) }),
  photo: scene,
  scenes: z.array(scene),
});
export const assetSchema = z.object({
  id,
  name: z.string().max(500),
  kind: z.enum(['image', 'video']),
  mime: z.string(),
  width: num.min(1).max(32768),
  height: num.min(1).max(32768),
  duration: num.min(0),
  createdAt: num,
  thumbnail: z.string().startsWith('data:image/').max(2000000),
  note: z.string().optional(),
});
